// JavaScript-код с созданием переменных

/*
Автор:
Нурислам
*/
// Создаем переменные с информацией о себе
const myName = "Нурислам";
const mySurname = "Шаяхметов";
let myFavoriteDrink = "чай";
let myFavoriteAnimal = "кот";
const myFavoriteProgrammingLanguage = "JavaScript";

// Выводим каждую переменную в консоль
console.log(myName);
console.log(mySurname);
console.log(myFavoriteDrink);
console.log(myFavoriteAnimal);
console.log(myFavoriteProgrammingLanguage);
